deconstrst/deconstrst.py
requirements.txt

If the `--submit` command-line argument is supplied, submit to the content store at the address specified by the `CONTENT_STORE` environment variable.

Publish to Content Service

---

setup.py

This was preventing `pip install -e .` from working, so hey.

Tiny config.py change.

---

deconstrst/deconstrst.py

I'd messed up the values yielded from `os.walk` on the first try. I should also correct the generated content IDs:
* They shouldn't include the file extension.
* "index" should be special-cased to map to the base resource.

Correct the content submission function.

---

deconstrst/deconstrst.py

This is for consistency with deconst/mapping-service#10.

Ensure that no content IDs have trailing slashes.

---

deconstrst/__init__.py
deconstrst/config.py
requirements.txt

Rather than trying to do some kind of painful bash scripting to decide whether or not content should be submitted after a build, make the decision based on:
1. The presence or absence of the necessary configuration environment variables.
2. The current git branch matching a regexp.
This should keep us non-Travis specific, too.

Use git instead of command-line arguments to control content submission

---

deconstrst/config.py
requirements.txt

This locks the preparer in to Travis. I'll need to rework it when we move to Strider (re: deconst/deconst-docs#10).

Use TRAVIS_PULL_REQUEST instead of git symbolic-ref.

---

deconstrst/deconstrst.py

Don't submit metadata envelopes within `{ "id": "...", "body": { ... } }` structures any more.

Upload files to the content store directly.

---

deconstrst/builder.py

Use the content service's asset API to publish images during the page build and use the CDN hrefs.

Publish images and other static content to the CDN.

---

README.md
deconstrst/builder.py
deconstrst/deconstrst.py

Adding a fieldlist to the beginning of a `.rst` file like this:
```
:deconst-layout: docs-page
```
Will result in that layout being specified in the metadata envelope.
A default layout should also be able to be set in `config.py`.

Allow documents to specify a layout.

---

Dockerfile
README.md
deconst-preparer-sphinx.sh

Provide a Docker image and wrapper script to easily invoke the preparer locally.
The next part of deconst/deconst-docs#49.

Dockerfile for development

---

README.md
deconstrst/builder.py

Allow per-page metadata to override the page title that Sphinx generates.

Override the page title

---

deconstrst/builder.py

If Sphinx would emit a table of contents for the current page, include the HTML for one in the envelope:
```json
{
"next": {
"title": "Data services",
"url": "../data_services/"
},
"toc": "<ul>\n<li><a class=\"reference internal\" href=\"#\">Storage and content delivery services</a><ul>\n<li><a class=\"reference internal\" href=\"#cloud-block-storage-at-a-glance\">Cloud Block Storage at a glance</a></li>\n<li><a class=\"reference internal\" href=\"#cloud-backup-at-a-glance\">Cloud Backup at a glance</a></li>\n<li><a class=\"reference internal\" href=\"#cloud-cdn-at-a-glance\">Cloud CDN at a glance</a></li>\n<li><a class=\"reference internal\" href=\"#cloud-files-at-a-glance\">Cloud Files at a glance</a></li>\n</ul>\n</li>\n</ul>\n",
"layout_key": "default",
"body": ".. snip ..", …
```

Include the table of contents in the envelope.

---

deconstrst/__init__.py
deconstrst/config.py

Allow configuration settings (for now, just `content-id-base`) to be specified in a JSON file at the Sphinx repository root. Environment variable settings take precedence, though, to allow you to temporarily override them for a specific build.

Apply configuration settings from .deconst.json.

---

deconstrst/__init__.py
deconstrst/config.py

The Jekyll preparer uses an underscore-prefixed `_deconst.json` file instead of a dotfile, because Jekyll copies all files verbatim unless their names start with an underscore. I'm making it consistent here even though Sphinx doesn't care about the filename, because it probably shouldn't be a hidden file, anyway.
I'm also updating the spec to accept the same camelCased setting.

Keep configuration consistent with the Jekyll preparer.

---

deconstrst/config.py

Setting the content ID base from `_deconst.json` previously bypassed the URL normalization I was doing. This normalizes the value either way and makes the error message less horribly wrong.
Fixes deconst/deconst-docs#138.

Normalize contentIDBase from _deconst.json.

---

deconstrst/builder.py

The configuration was being read twice, once in `__init__.py` and once in `builder.py`, but I was only applying the `_deconst.json` overrides in `__init__.py`.
I'm not a huge fan of the duplication here, but this will do for now.

Read _deconst.json in the builder too.

---

deconstrst/builder.py

Rather than rely on server-side content type inference, let's derive them locally.
Relevant to deconst/client#5.

Derive a mimetype for each asset.

---

README.md
deconstrst/__init__.py
deconstrst/builders/serial.py
deconstrst/builders/single.py
deconstrst/deconstrst.py

O mighty @smashwilson please tell me what I've done wrong :wink: 
Really, there's a lot of copy/paste from https://github.com/sphinx-doc/sphinx/blob/1.3.1/sphinx/builders/html.py#L894 that could _probably_ be done better by just calling the parent class's method.
There's probably also room at some point to combine the `_publish_entry()` stuff so it can be reused and not just copy/pasted as I've done here.
* Allow preparer to be run against another directory instead of just the current directory. Mostly to scratch my own itch and test easily. `deconstrst.main('/usr/content-repo')`
* Add `DeconstSingleJSONBuilder` that borrows from `SingleFileHTMLBuilder` but builds a JSON envelope with a big, beautiful ToC
* Allow content repos to choose which builder they want (`deconst-single` or …

Adding SingleJSON builder that acts like singlehtml, but for deconst

---

setup.py

It turns out that Python doesn't include packages in an egg unless it's listed in the `packages` field. This adds the new "builders" package in the list.
Fixes deconst/deconst-docs#161.

Include deconstrst.builders in setup.py metadata

---

Dockerfile

Change the path that we use to map the content repository to be consistent with the changed path that the Jekyll preparer uses.
This will break the local Deconst client until I can push another release.

Change the path of the content repository

---

deconstrst/__init__.py
deconstrst/deconstrst.py

This was a little ambiguous as to where exactly `conf.py` should be found, resulting in ENOENT errors. This change declares that it will be directly within the source directory.

be more specific about where conf.py should be found

---

deconstrst/builders/single.py

For reasons unknown, `render_partial()` renders the body doctree _twice_. Source-diving into Sphinx a little reveals that the SingleFileHTMLBuilder [calls `write_doc()`](https://github.com/sphinx-doc/sphinx/blob/1.3.1/sphinx/builders/html.py#L430-L445) to convert the body doctree into HTML rather than `render_partial()`, so I ported the relevant bits from that into our builder and it seems to be working properly now.
This is the root cause of rackerlabs/nexus-control#176.
So about those preparer tests... :wink:

Duplicated content with the deconst-single builder

---

Dockerfile

This'll do nicely:
```bash
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
after               latest              d745ec15f28c        2 minutes ago       101.4 MB
before              latest              b5a442415a0d        8 minutes ago       735.5 MB
```

Base the Docker image on Alpine instead.

---

deconstrst/builders/single.py

This prevents the deconst preparer from changing _all_ links with anchors to anchors on the current page.
Re: deconst/deconst-docs#182

Leave absolute URLs with anchors alone.

---

README.md
deconstrst/builders/serial.py
deconstrst/builders/single.py
deconstrst/config.py
deconstrst/deconstrst.py

It makes me sad to do this, but I don't want to drop :moneybag: on a real TLS cert for [deconst.horse](https://deconst.horse/) with letsencrypt coming out in a few short weeks. It'll be nice for quick personal instances with self-signed certs too.

Option to disable TLS verification

---

deconstrst/builders/__init__.py
deconstrst/builders/serial.py
deconstrst/builders/single.py

Allow content to be marked as `unsearchable`.
References deconst/content-service#63 and deconst/deconst-docs#187.

Unsearchable

---

README.md
deconstrst/builders/__init__.py
deconstrst/builders/serial.py
deconstrst/builders/single.py

This is more important with the final work on deconst/deconst-docs#187.

Support global and per-document categories.

---

deconstrst/builders/serial.py
deconstrst/builders/single.py
deconstrst/config.py

Looks for a `meta` key in `_deconst.json` and adds everything in there to a matching key on each content envelope. If the individual page has also specified metadata, the two are merged, allowing individual documents to override repository-wide metadata.
Also adds a `githubUrl` key to `_deconst.json` which is used to derive a GitHub issues URL, which is added to the repository-wide metadata. This smells like vendor lock-in with GitHub, and we should perhaps just allow content owners to provide an issues URL, whether it be Github, Redmine, et al.

Add repo-wide metadata and a Github Issues URL

---

deconstrst/__init__.py
deconstrst/config.py

Accept a `CONTENT_ROOT` environment variable to prepare content from paths other than the cwd, notably `--volumes-from` mounted paths.
In service of deconst/strider-deconst-content#3.

Optionally accept a CONTENT_ROOT.

---

deconstrst/builders/serial.py
deconstrst/builders/single.py

I was previously checking whether the config object has the `github_url` attribute, but it always will because we assign it a default value. Checking for it to equal the default value instead.

Github Edit URLs should not be generated when no repo URL is provided

---

deconstrst/__init__.py
deconstrst/builders/serial.py
deconstrst/builders/single.py
deconstrst/builders/writer.py
deconstrst/config.py

When not submitting content to a content store API, write metadata envelopes to `ENVELOPE_DIR` with filenames of `<content-id>.json` and copy assets to `ASSET_DIR`.
Fixes #52.

Adhere to the new preparer protocol

---

deconstrst/builders/writer.py

If assets are included from outside the `_images` directory, copy them into the `ASSET_DIR` anyway.
Fixes deconst/submitter#16.

Improve handling of assets outside the asset directory

---

deconstrst/builders/envelope.py

It turns out that the `source_suffix` already includes the leading `.`.
Fixes #65.

Double dot in github_edit_url.

---

requirements.txt

Closes INFODEV-2785
Relates to https://github.com/deconst/preparer-sphinx/pull/78/

Fix for CVE-2018-18074
